version: '3.3'

services:
  nginx_https:
    container_name: mydomain_com_nginx_https
    image: nginx:latest
    restart: always
    ports:
      - 443:443
    volumes:
      - ./ca:/etc/nginx/ca
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./html:/usr/share/nginx/html
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - TZ=Asia/Shanghai
  nginx_http:
    container_name: mydomain_com_nginx_http
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./http/conf.d:/etc/nginx/conf.d
      - ./http/html:/usr/share/nginx/html
      - ./http/log:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      - TZ=Asia/Shanghai
