version: '3.5'

services:
  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=muserquantity
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '2'
        reservations:
          memory: 512m
          cpus: '0.5'
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/db-init.js:ro