version: '3.5'
services:
  mysql:
    image: redis
    restart: always
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data:rw
      - ./logs:/logs
    command:  redis-server /usr/local/etc/redis/redis.conf --requirepass "muserquantity"